version: '3'
services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    networks:
      - ApiToDB_network
    ports:
     - 3600:3600
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contactsjpa

  backend-java:
    image: "restapp1:latest"
    container_name: backend-java
    ports:
      - 9090:9090
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/contactsjpa
    networks:
      - ApiToDB_network
    depends_on:
      - mysqldb
networks:
  ApiToDB_network:
    driver: bridge